Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/*_controller.rb'
    - 'app/helpers/*_helper.rb'
    - 'config/application.rb'
    - 'db/migrate/*'

AllCops:
  Exclude:
    - 'db/schema.rb'
